name: Build App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

  build_upload:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build application
        run: pyinstaller --onefile Life.py
        
      - name: Archicve
        run: |
             sudo apt-get update
             sudo apt-get install zip
             zip -r arhive.zip *
             
      - name: Debug
        run: |
          ls
          cd dist
          ls
     
      - name: Upload artifacts
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.gkey }}
          filename: "archive.zip"
          folderId: ${{ secrets.folder_id }}
          name: "archive.zip"
          overwrite: "true"
